spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Kirill
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: false
  liquibase:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher